services:
  server:
    container_name: ${SERVER_CONTAINER_NAME}
    image: ${SERVER_IMAGE_TAG}
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      target: ${SERVER_BUILD_TARGET}
    environment:
      ALLOWED_HOSTS: ${SERVER_ALLOWED_HOSTS}
      URL: ${SERVER_URL}
      GIN_MODE: ${SERVER_MODE}
      PORT: ${SERVER_PORT}
    command: ${SERVER_COMMAND}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ${SERVER_VOLUMES_APP}
      - bingo-modules:/go/pkg/mod
    restart: ${SERVER_RESTART}

volumes:
  bingo-server:
    name: bingo-server
  bingo-modules:
    name: bingo-modules
