root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  pre_cmd = ["make generate-required"]
  cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/bingo"
  post_cmd = []
  delay = 1000
  exclude_dir = [
    "pkg/cmd/server/static/dist",
    "pkg/context/binary/infrastructure/compiler/app",
    "pkg/context/binary/infrastructure/compiler/embed",
    "pkg/context/binary/infrastructure/compiler/temp"
  ]
  exclude_file = []
  exclude_regex = [
    "^.*_test\\.go$",
    "^.*\\.mother\\.go$",
    "^.*_templ\\.go$"
  ]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = [
    "pkg"
  ]
  include_ext = [
    "go",
    "html",
    "templ",
    "tmpl",
    "tpl"
  ]
  include_file = []
  kill_delay = "5s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
